export const wordData = [
  { id: 1, text: "Couple Therapy", value: "64px", color: "#c25849" },
  { id: 2, text: "Life crisis", value: "36px", color: "#5AB2BE" },
  { id: 3, text: "Grief", value: "64px", color: "#c25849" },
  { id: 4, text: "Health issues", value: "20px", color: "#5AB2BE" },
  { id: 5, text: "LGBT", value: "36px", color: "#5AB2BE" },
  { id: 6, text: "Meaning", value: "20px", color: "#5AB2BE" },
  { id: 8, text: "Advice and support", value: "20px", color: "#5AB2BE" },
  { id: 9, text: "Fear", value: "36px", color: "#5AB2BE" },
  { id: 10, text: "Family Therapy", value: "64px", color: "#c25849" },
  { id: 11, text: "Life Purpose", value: "36px", color: "#5AB2BE" },
  { id: 12, text: "Depression", value: "20px", color: "#5AB2BE" },
  { id: 13, text: "Divorce", value: "36px", color: "#5AB2BE" },
  { id: 14, text: "Stress", value: "36px", color: "#5AB2BE" },
  { id: 15, text: "Relationships", value: "3.5rem", color: "#5AB2BE" },
  { id: 16, text: "Cancer", value: "20px", color: "#5AB2BE" },
  { id: 17, text: "Workplace Issues", value: "36px", color: "#5AB2BE" },
  { id: 18, text: "Individual Therapy", value: "64px", color: "#c25849" },
  { id: 19, text: "Trauma", value: "64px", color: "#c25849" }
]