export const wordCloudData = [
  { id: 1, text: "Couple Therapy", value: 64 },
  { id: 2, text: "Life crisis", value: 36 },
  { id: 3, text: "Grief", value: 64 },
  { id: 4, text: "Health issues", value: 32 },
  { id: 5, text: "LGBT", value: 36 },
  { id: 6, text: "Meaning", value: 32 },
  { id: 8, text: "Advice and support", value: 2 },
  { id: 9, text: "Fear", value: 36 },
  { id: 10, text: "Family Therapy", value: 64 },
  { id: 11, text: "Life Purpose", value: 36 },
  { id: 12, text: "Depression", value: 32 },
  { id: 13, text: "Divorce", value: 36 },
  { id: 14, text: "Stress", value: 36 },
  { id: 15, text: "Relationships", value: 64 },
  { id: 16, text: "Cancer", value: 32 },
  { id: 17, text: "Workplace Issues", value: 36 },
  { id: 18, text: "Individual Therapy", value: 64 },
  { id: 19, text: "Trauma", value: 64 }
]
